# Generated by Django 2.2.7 on 2019-11-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogss', '0003_auto_20191116_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='readed_num',
            field=models.IntegerField(default=0),
        ),
    ]
