# Generated by Django 2.2.7 on 2019-11-17 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogss', '0004_blog_readed_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='readed_num',
        ),
    ]
