# Generated by Django 2.2.7 on 2019-12-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogss', '0005_remove_blog_readed_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
